Introduction

In [ ]:
import numpy as np
#numpy <- writen in c, optimized for linear Algebra
a = [1,2,3,4,5]

print(a[3])
print(a)

In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a[2:])

#numpy array separated by spacing

In [ ]:
# multilayer
a_mul = np.array([[[1,2,3, 0],
                [4,5,6, 0],
                [7,8,9, 0]],
                [[4,5,6, 0],
                [7,6,0, 0],
                [1,2,3, 0]]])

print (a_mul.shape) #size - as matrix

# (# of matrices, row, column )
# **only if matrices are of same size (homogeneous)
# all element should be included in a single list form as a whole [ ]

print(a_mul.ndim) #dimension - depth

# Q - f vector(x,y,z) perspective?

print(a_mul.size) #amount of element
print(a_mul.dtype) #


Datatype

In [4]:
import numpy as np

a = np.array([[1,2,3],
             [4, "8" ,5],
             [7,8,9]] , dtype = np.float32 )
             #Q - dtype = np.int32 example, function? + what does the number after a typename mean?

print(a.dtype)
# < U# - Unicode string with less than # Characters
print(a.itemsize)
# memory that a single item in array uses
# in this case, 21*4(bytes for unicode)
print(a[0][0])
print(type(a[0][0]))
print(a[0][0].dtype)

float32
4
1.0
<class 'numpy.float32'>
float32


##### unicode : universial standard/code for each text in computer. 
assigned to each character/number/symbols, etc. Usually takes up 4 bytes of memory (integer takes 28)
    + ) practically the same as string, except for encoding systems created before unicode

##### How numpy allocates memory
The number as in U21 <- fit for the longest (unicord) title for convinience, as a fixed-sized lot ; can only tell the size of a single element

##### Numpy's Upcasting Process
converts other data types into the most general one(string in this case)
+ ) as object in the exampe below

In [89]:
import numpy as np

d = {'1' : 'A'}

a = np.array([[1,2,3],
             [4, d ,5],
             [7,8,9]])

print(a.dtype)
print(type(a[1][0]))

# is .dtype result always pre-defined?


object
<class 'int'>


print(a[1][0].dtype) :
error occurs because standard Python integers don't have .dtype property (property does not exist)
* unlike other numpy elements, standard Python integer contains multiple info. 
for it to have a dtype property, the property needs to be clarified like the previous example.
'unoptimized'


other ex. being )
all-string array w. designated dtype
=> <class 'numpy.str_'>

In [90]:
# arrays with default value

import numpy as np
a = np.full((2,3,4), 9)
# full function - create an array w. (size/shape, content)
print(a)

b = np.zeros((10,5,2))
print(b)

c = np.ones((10,5,2))

d = np.empty((3,3,3))
print(d)
# allocates memory w/o value (reserves space for such size)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.11260280e-306 1.89146896e-307 7.56571288e-307]
  [3.11525958e-307 1.24610723e-306 1.37962320e-306]]

 [[1.29060871e-306 2.22518251e-306 1.33511969e-306]
  [1.78022342e-306 1.05700345e-307 3.11525958e-307]
  [1.69118108e-306 8.06632139e-308 1.20160711e-306]]

 [[1.69119330e-306 1.78021663e-306 8.90067741e-308]
  [8.34426464e-308 1.11260483e-306 1

Sequence generation

In [91]:
import numpy as np

x_values = np.arange(0, 1000,5) #beginning,end,step size
print(x_values)

x_values = np.linspace(0,1000, 101) #beginning, end, number of values
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]
[   0.   10.   20.   30.   40.   50.   60.   70.   80.   90.  100.  110.
  120.  130.  140.  150.  160.  170.  180.  190.  200.  210.  220.  230.
  240.  250.  260.  270.  280.  290.  300

In [92]:
# import numpy as np

print(np.nan) #not a number 
#Use : filling vacant # in huge dataset
print(np.inf) #infinity 
#Use : when needed to return infinity value (ex.division by 0)

print(np.isnan(np.nan)) 
print(np.isinf(np.inf))
# checking if not a number/infinity

#why does these return the type of np. content?
print(np.sqrt(-1)) #sqrt : square root
print(np.array([10])/0)

nan
inf
True
True
nan
[inf]


C:\Users\saige\AppData\Local\Temp\ipykernel_32984\3519695056.py:13: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1)) #sqrt : square root
C:\Users\saige\AppData\Local\Temp\ipykernel_32984\3519695056.py:14: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


Mathematical Operations with Numpy
- enables subtract, multiplication, division, etc. of array not supported in basic python list

In [93]:

l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1*5) #repeat the element in list 5 times
print(a1*5) #multiply each element by 5

print(l1 + l2) #combine into a new list
# print(l2+5) - TypeError

print(a2+5)
print(a1*a2) #functions as vector mulplication - like inner product? (when arrays are of same size)

##---- 

a1 = np.array([1,2,3])
a2 = np.array([[1],
            [2]])
            

# print(a1+a2) - matrices has to be of same size

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[11 12 13 14  5]
[ 6 14 24 36  0]


other use of numpy in mathematical calculations

In [94]:
a = np. sqrt([[1,2,3],
            [4,5,6]])

print(np.sqrt(a))

print(np.log(a))

[[1.         1.18920712 1.31607401]
 [1.41421356 1.49534878 1.56508458]]
[[0.         0.34657359 0.54930614]
 [0.69314718 0.80471896 0.89587973]]


[Methods] Adding elements
np. (function) (array, index, axis)


In [95]:
a = np. array([[1,2,3]])

a = np.append(a, [7,8,9])

a = np. insert(a, 3, [4,5,6])
# third position - adding [4,5,6] from index 3 of list a

# certain libraries(np, pd, etc.) doesn't change the value - needs manuall change w/ a = ~ 

print(a)


[1 2 3 4 5 6 7 8 9]


[Methods] Deleting
np.delete(array, index, axis)

if axis # = 0 : (idx + 1)th row / 
if axis # = 1 : (idx + 1)th column

In [96]:
a = np. array([[1,2,3],
                [4,5,6]])

print(np.delete(a,2)) #no axis provided : delete the element at # index

print(np.delete(a,0,0)) # delete 1st row 
print(np.delete(a,1,0)) #delete 2nd row

print(np.delete(a,0,1)) #delete 1st column (idx =  0)
print(np. delete(a, 1, 1)) #delete 2nd column (idx =  1)
print(np.delete(a,2,1)) # delete 3rd column 


[1 2 4 5 6]
[[4 5 6]]
[[1 2 3]]
[[2 3]
 [5 6]]
[[1 3]
 [4 6]]
[[1 2]
 [4 5]]


[Methods] Structuring Methods
* 'view' of an list/array : no other array is being created / modification impacts the original array

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

# print(a.shape)
print(a.reshape(5,4)) #possible only if  compatible w. no blank idx
print(a.reshape(10,2))
print(a.reshape(2,5,2))

a.reshape(1,20)
print(a)

a.resize((5,4)) #requires tuple
print(a)

print(a.flatten()) # flattened copy of an array
print(a.ravel()) # returns flat view


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2 100   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]
 [ 17  18  19  20]]


[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]


In [ ]:
var1 = a.flatten()
var1[2] = 100
print(var1) #original array is not modified - flattened 'view'
print(a)

var2 = a.ravel()
var2[2] = 100
print(var2) #original array is modified
print(a)

### from the video this code returns a list w. standard python integer unlike mine. WHY?
var = [ v for v in a.flat ] #similar to flatten Method, creates new list w. elements of the array
print(var)


[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2 100   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]
 [ 17  18  19  20]]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2 100   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]
 [ 17  18  19  20]]
[np.int64(1), np.int64(2), np.int64(100), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]


In [ ]:
#Transposing

a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

print(a.transpose())
print(a.T) #Both possible
print(a.swapaxes(0,1)) # can choose the axes you want to swap - works when w. multiple dimensions



[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


Joining/Spliting arrays

In [ ]:
#Joining arrays - np.concatenate, np.stack
a1 = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
a2 = np.array([[11,12,13,14,15], 
                [16,17,18,19,20]])

#concatenate - works on pre-existing dimensions
#different results by axis
a = np.concatenate((a1,a2), axis =0) #row-wise
print(a)

a = np.concatenate((a1,a2), axis =1) #column-wise
print(a)

#stack - works on new dimensions - 2 additional list 
a = np.stack((a1,a2))
print(a)
# tuple input required

print(a = np.vstack((a1,a2)))

print(a = np.hstack((a1,a2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [ ]:
#splitting arrays
a = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15], 
                [16,17,18,19,20]])

# np.split (array, # of resulting array, axis)
print(np.split(a, 2, axis = 0))
print(np.split(a, 5, axis = 1))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]
[array([[ 1],
       [ 6],
       [11],
       [16]]), array([[ 2],
       [ 7],
       [12],
       [17]]), array([[ 3],
       [ 8],
       [13],
       [18]]), array([[ 4],
       [ 9],
       [14],
       [19]]), array([[ 5],
       [10],
       [15],
       [20]])]


[Aggregate Functions]

In [ ]:
print(a.min())
print(a.max())
print(a.mean())
print(a.std()) # standard deviation
print(a.sum())
print(np.median(a))

1
20
10.5
5.766281297335398
210
10.5


[Numpy Random]

In [150]:
number = np.random.randint(100)
print(number)

numbers = np.random.randint(90, 100, size = (2,3,4)) #min/max
print(numbers)

numbers = np.random.binomial(10, p = 0.5, size = (5,10))
print(numbers)

numbers = np.random.normal(loc = 170, scale = 15, size = (5,10))
print(numbers)

numbers = np.random.choice([10, 20, 30,40,50], size = (5,10))
print(numbers)

19
[[[97 90 95 96]
  [94 92 92 92]
  [92 92 90 96]]

 [[99 98 90 91]
  [91 98 94 94]
  [96 96 93 92]]]
[[4 5 4 5 5 3 6 6 3 5]
 [5 6 5 2 5 4 6 2 5 5]
 [4 6 5 6 5 6 7 7 5 7]
 [6 4 7 4 6 4 6 7 6 4]
 [6 9 4 4 4 7 4 2 4 6]]
[[162.95043021 177.31390106 150.23577878 166.17889521 148.94321582
  155.56827214 178.81206616 155.63938886 169.37419109 156.20826926]
 [152.28302121 157.71556441 147.25509753 184.23697607 195.10028743
  186.16579405 195.11150968 177.40150234 157.26630372 173.55098394]
 [164.2077177  181.912088   158.63128441 179.43276601 159.08267963
  161.94021865 194.41960985 179.10960403 151.30013047 156.49185374]
 [162.89922598 157.32585579 155.37538748 193.33820251 166.72982091
  170.58801391 192.20446616 165.86739266 126.0175755  176.21595198]
 [138.41637757 159.33530176 182.26159025 171.91859535 191.36167551
  198.97544843 166.90062112 143.47407664 166.51862516 141.2748279 ]]
[[50 20 20 20 50 50 10 50 40 20]
 [40 20 30 20 20 30 10 20 10 30]
 [50 20 20 40 50 10 40 10 40 10]
 [10 3

[ Save / Import ]

In [ ]:
np.save("myarray.npy",a)
a = np.load("myarray.npy")
print(a)

#other saving format
np.savetxt("myarray.csv", a, delimiter = ",")
np.save

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
